### ISSUE TITLE
How do I install and use?

### ISSUE THREAD

**Issue by robsonfelix** [magic7s/intelbras-solar#1]
I have searched online on something that details how this gets installed and configured, but could not find anything.

I have been able to add this repository to HACS, to add the configuration to configuration.yaml (including secrets), but when I try to add the integration through Settings -> Integrations -> Add Integration -> Intelbras Solar. but it gives me a message: "This device can not be added from the UI".

Any help would be appreciated.

**Comment by magic7s** [comment]
Add the username and password to your configuration.yaml file.

```yaml
intelbras_solar:
  username: !secret intelbras_username
  password: !secret intelbras_password
```
